categories:
  - name: 常用网站
    icon: fas fa-star
    sites:
      - name: Linux.do
        url: https://linux.do/
        icon: fab fa-linux
        description: 新的理想型社区
      - name: 里屋
        url: https://www.253874.net/
        icon: far fa-warehouse
        description: 青少年技术论坛
      - name: GitHub
        url: https://www.github.com
        icon: fab fa-github
        description: 代码托管平台
      - name: 我的群晖
        url: https://20171127.xyz:874
        icon: far fa-desktop
        description: Synology Disktaion
      - name: S1论坛
        url: https://stage1st.com/2b/
        icon: far fa-tire
        description: 卓明谷
      - name: 今日热榜
        url: https://tophub.today/
        icon: far fa-paragraph
        description: 今日热榜官网
  - name: 自建网站
    icon: far fa-atom
    sites:
      - name: LUCKY
        url: https://nas.20171127.xyz:12800/zgf/#/about
        icon: far fa-leaf-maple
        description: 内部服务
      - name: PDF文件编辑
        url: https://pdf.20171127.xyz:12803/?lang=zh_CN
        icon: far fa-file-pdf
        description: PDF文件编辑
      - name: 文件快递柜
        url: https://file.20171127.xyz:12803/
        icon: far fa-mailbox
        description: 文件快递柜
      - name: LibreTV
        url: https://brics.dpdns.org/
        icon: fas fa-code
        description: 免费在线观看平台
  - name: 开发工具
    icon: fas fa-tools
    sites:
      - name: VS Code
        url: https://code.visualstudio.com
        icon: fas fa-code
        description: 强大的代码编辑器
      - name: Postman
        url: https://www.postman.com
        icon: fas fa-paper-plane
        description: API调试工具
      - name: Git
        url: https://git-scm.com
        icon: fab fa-git-alt
        description: 版本控制工具
      - name: Docker
        url: https://www.docker.com
        icon: fab fa-docker
        description: 容器化平台
  - name: 设计资源
    icon: fas fa-palette
    sites:
      - name: Figma
        url: https://www.figma.com
        icon: fab fa-figma
        description: 在线设计工具
      - name: Dribbble
        url: https://dribbble.com
        icon: fab fa-dribbble
        description: 设计师社区
      - name: Behance
        url: https://www.behance.net
        icon: fab fa-behance
        description: 创意设计平台
      - name: IconFont
        url: https://www.iconfont.cn
        icon: fas fa-icons
        description: 图标资源库
  - name: 在线工具
    icon: fas fa-wrench
    sites:
      - name: JSON Editor
        url: https://jsoneditoronline.org
        icon: fas fa-code-branch
        description: JSON在线编辑器
      - name: Can I Use
        url: https://caniuse.com
        icon: fas fa-browser
        description: 浏览器兼容性查询
      - name: TinyPNG
        url: https://tinypng.com
        icon: fas fa-compress
        description: 图片压缩工具
      - name: Carbon
        url: https://carbon.now.sh
        icon: fas fa-code
        description: 代码图片生成器
